apiVersion: apps/v1
kind: Deployment
metadata:
  name: eepy-site
spec:
  selector:
    matchLabels:
      app: eepy-site
  template:
    metadata:
      labels:
        app: eepy-site
    spec:
      containers:
      - name: eepy-site
        image: kokuzo.tailc38f.ts.net/eepy-site:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
        env:
        - name: SECRETS_FILE
          value: /secrets/secrets.json
        volumeMounts:
        - name: secrets
          mountPath: /secrets
          readOnly: true
      volumes:
      - name: secrets
        secret: 
          secretName: eepy-site-secrets-file
          items:
          - key: secrets.json
            path: secrets.json
