name: Nix Flake action
on:
  pull_request:
  push:
jobs:
  nix-build:
    name: upload-docker-image
    runs-on: eepy-runner-set
    steps:
    - uses: actions/checkout@v4
    # - uses: cachix/install-nix-action@v31
    - run: nix run -L '.#pushDockerImageActions'
